# Generated by Django 4.1.7 on 2023-03-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('image', models.ImageField(upload_to='booking')),
                ('cou_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.course')),
            ],
        ),
    ]
