# Generated by Django 4.1.7 on 2023-03-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_name', models.CharField(max_length=255)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('Place', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=200)),
                ('Willing_time', models.TimeField()),
                ('Booked_on', models.DateField(auto_now=True)),
                ('cou_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.course')),
            ],
        ),
    ]
