# Generated by Django 4.1.7 on 2024-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_coursebook_remove_video_cou_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebook',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500),
        ),
    ]
