# Generated by Django 4.1.7 on 2024-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_coursebook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebook',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
