# Generated by Django 4.1.7 on 2024-01-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_alter_coursebook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebook',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('heading', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video')),
                ('cou_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.course')),
            ],
        ),
    ]
