# Generated by Django 4.1.7 on 2024-01-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_alter_coursebook_discount_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cou_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.coursebook'),
        ),
    ]
